version: '3.8'

services:
  prestashop-remove:
    image: prestashop/prestashop:1.7.8.6-apache
    ports:
      - 8007:80
      - 9004:9000
    depends_on:
      - mariadb-remove
    volumes:
      - prestashop-remove:/var/www/html
      - ./:/var/www/html/modules/webo_removeallitem
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb-remove
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_FOLDER_INSTALL=installDirHasToBeRenamed
      - PS_FOLDER_ADMIN=admin1234
      - PS_LANGUAGE=pl
      - ADMIN_MAIL=support@webo.agency
      - ADMIN_PASSWD=password
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8007

  mariadb-remove:
    image: mariadb:10.8.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
      - db-remove:/var/lib/mysql

  phpmyadmin-remove:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb-remove
    ports:
      - 83:80
    environment:
      - PMA_HOST=mariadb-remove
      - PMA_USER=root
      - PMA_PASSWORD=root

  openssh-server-remove:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server-remove
    hostname: openssh-server #optional
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/London
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=prestashop #optional
    volumes:
      - config-remove:/config
      - prestashop-remove:/home/prestashop
    ports:
      - 2224:2222
    restart: unless-stopped

volumes:
  prestashop-remove:
  config-remove:
  db-remove:
